server:
  port: 9090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rodolfocruzbsb/maisvida-configuratios.git
          skipSslValidation: true
          username: ${git.user}
          password: ${git.password}
          clone-on-start: true
          delete-untracked-branches: true          
  security:
   user:
     name: usr_app_configuration
     password: qwe123

